-- ============================================================================
-- ATO Fraud Detection Prototype - RBAC Grants
-- Role hierarchy and privilege setup
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- Custom roles
CREATE ROLE IF NOT EXISTS ATO_FRAUD_ADMIN
    COMMENT = 'Full admin for ATO fraud prototype';
CREATE ROLE IF NOT EXISTS ATO_FRAUD_ANALYST
    COMMENT = 'Fraud analyst: read scored data, query semantic views, search policies';
CREATE ROLE IF NOT EXISTS ATO_FRAUD_OPS
    COMMENT = 'Fraud operations: view PII, override rules, investigate cases';
CREATE ROLE IF NOT EXISTS ATO_COMPLIANCE
    COMMENT = 'Compliance: manage policy rules, view regulatory data, audit';
CREATE ROLE IF NOT EXISTS ATO_DATA_ENGINEER
    COMMENT = 'Data engineer: manage pipelines, retrain models';

-- Role hierarchy
GRANT ROLE ATO_FRAUD_ANALYST TO ROLE ATO_FRAUD_OPS;
GRANT ROLE ATO_FRAUD_OPS TO ROLE ATO_FRAUD_ADMIN;
GRANT ROLE ATO_COMPLIANCE TO ROLE ATO_FRAUD_ADMIN;
GRANT ROLE ATO_DATA_ENGINEER TO ROLE ATO_FRAUD_ADMIN;
GRANT ROLE ATO_FRAUD_ADMIN TO ROLE ACCOUNTADMIN;

-- Database-level grants
GRANT USAGE ON DATABASE ATO_FRAUD_DB TO ROLE ATO_FRAUD_ADMIN;
GRANT USAGE ON DATABASE ATO_FRAUD_DB TO ROLE ATO_FRAUD_ANALYST;
GRANT USAGE ON DATABASE ATO_FRAUD_DB TO ROLE ATO_FRAUD_OPS;
GRANT USAGE ON DATABASE ATO_FRAUD_DB TO ROLE ATO_COMPLIANCE;
GRANT USAGE ON DATABASE ATO_FRAUD_DB TO ROLE ATO_DATA_ENGINEER;

-- Schema-level grants: ATO_FRAUD_ANALYST (read-only on scored data + semantic)
GRANT USAGE ON SCHEMA ATO_FRAUD_DB.SCORING TO ROLE ATO_FRAUD_ANALYST;
GRANT USAGE ON SCHEMA ATO_FRAUD_DB.SEMANTIC TO ROLE ATO_FRAUD_ANALYST;
GRANT USAGE ON SCHEMA ATO_FRAUD_DB.POLICY_ENGINE TO ROLE ATO_FRAUD_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ATO_FRAUD_DB.SCORING TO ROLE ATO_FRAUD_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ATO_FRAUD_DB.POLICY_ENGINE TO ROLE ATO_FRAUD_ANALYST;

-- Schema-level grants: ATO_FRAUD_OPS (read raw + scoring + policy)
GRANT USAGE ON SCHEMA ATO_FRAUD_DB.RAW TO ROLE ATO_FRAUD_OPS;
GRANT SELECT ON ALL TABLES IN SCHEMA ATO_FRAUD_DB.RAW TO ROLE ATO_FRAUD_OPS;

-- Schema-level grants: ATO_COMPLIANCE (manage policy rules)
GRANT USAGE ON SCHEMA ATO_FRAUD_DB.POLICY_ENGINE TO ROLE ATO_COMPLIANCE;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA ATO_FRAUD_DB.POLICY_ENGINE TO ROLE ATO_COMPLIANCE;

-- Schema-level grants: ATO_DATA_ENGINEER (manage all schemas)
GRANT USAGE ON ALL SCHEMAS IN DATABASE ATO_FRAUD_DB TO ROLE ATO_DATA_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA ATO_FRAUD_DB.RAW TO ROLE ATO_DATA_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA ATO_FRAUD_DB.FEATURES TO ROLE ATO_DATA_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA ATO_FRAUD_DB.SCORING TO ROLE ATO_DATA_ENGINEER;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE ATO_FRAUD_WH TO ROLE ATO_FRAUD_ADMIN;
GRANT USAGE ON WAREHOUSE ATO_FRAUD_WH TO ROLE ATO_FRAUD_ANALYST;
GRANT USAGE ON WAREHOUSE ATO_FRAUD_WH TO ROLE ATO_FRAUD_OPS;
GRANT USAGE ON WAREHOUSE ATO_FRAUD_WH TO ROLE ATO_COMPLIANCE;
GRANT USAGE ON WAREHOUSE ATO_FRAUD_WH TO ROLE ATO_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE ATO_ML_WH TO ROLE ATO_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE ATO_SEARCH_WH TO ROLE ATO_DATA_ENGINEER;

-- Cortex AI access (required for Cortex Analyst, Search, Agent)
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ATO_FRAUD_ANALYST;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ATO_FRAUD_OPS;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ATO_COMPLIANCE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ATO_DATA_ENGINEER;

-- Semantic view creation privilege
GRANT CREATE SEMANTIC VIEW ON SCHEMA ATO_FRAUD_DB.SEMANTIC TO ROLE ATO_DATA_ENGINEER;
