-- ============================================================================
-- Governance: Role-Based Access Control (RBAC) Architecture
-- Creates enterprise security personas and least-privilege role hierarchy
-- Personas:
--   1. ATO_FRAUD_ADMIN        - Full schema DDL, security policy management
--   2. ATO_FRAUD_INVESTIGATOR - Unmasked PII access, manual case actions, overrides
--   3. ATO_FRAUD_ANALYST      - Masked PII analytics, Streamlit dashboard access
--   4. ATO_COMPLIANCE_OFFICER - Audit log access, policy rule engine inspection
-- ============================================================================

USE DATABASE ATO_FRAUD_DB;

-- 1. Create Functional Security Roles
CREATE ROLE IF NOT EXISTS ATO_FRAUD_ADMIN;
CREATE ROLE IF NOT EXISTS ATO_FRAUD_INVESTIGATOR;
CREATE ROLE IF NOT EXISTS ATO_FRAUD_ANALYST;
CREATE ROLE IF NOT EXISTS ATO_COMPLIANCE_OFFICER;

-- 2. Build Role Hierarchy (Inheritance to ACCOUNTADMIN)
GRANT ROLE ATO_FRAUD_ANALYST TO ROLE ATO_FRAUD_INVESTIGATOR;
GRANT ROLE ATO_COMPLIANCE_OFFICER TO ROLE ATO_FRAUD_ADMIN;
GRANT ROLE ATO_FRAUD_INVESTIGATOR TO ROLE ATO_FRAUD_ADMIN;
GRANT ROLE ATO_FRAUD_ADMIN TO ROLE ACCOUNTADMIN;

-- 3. Database & Schema Grants
GRANT USAGE ON DATABASE ATO_FRAUD_DB TO ROLE ATO_FRAUD_ANALYST;
GRANT USAGE ON SCHEMA ATO_FRAUD_DB.RAW TO ROLE ATO_FRAUD_ANALYST;
GRANT USAGE ON SCHEMA ATO_FRAUD_DB.FEATURES TO ROLE ATO_FRAUD_ANALYST;
GRANT USAGE ON SCHEMA ATO_FRAUD_DB.SCORING TO ROLE ATO_FRAUD_ANALYST;
GRANT USAGE ON SCHEMA ATO_FRAUD_DB.POLICY_ENGINE TO ROLE ATO_FRAUD_ANALYST;
GRANT USAGE ON SCHEMA ATO_FRAUD_DB.SEMANTIC TO ROLE ATO_FRAUD_ANALYST;
GRANT USAGE ON SCHEMA ATO_FRAUD_DB.APP TO ROLE ATO_FRAUD_ANALYST;

-- 4. Warehouse Grants
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ATO_FRAUD_ANALYST;

-- 5. Table & Dynamic Table Read Privileges
GRANT SELECT ON ALL TABLES IN SCHEMA ATO_FRAUD_DB.RAW TO ROLE ATO_FRAUD_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA ATO_FRAUD_DB.FEATURES TO ROLE ATO_FRAUD_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA ATO_FRAUD_DB.SCORING TO ROLE ATO_FRAUD_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ATO_FRAUD_DB.POLICY_ENGINE TO ROLE ATO_FRAUD_ANALYST;

-- 6. Cortex Search & Procedure Grants
GRANT USAGE ON CORTEX SEARCH SERVICE ATO_FRAUD_DB.SEMANTIC.ATO_POLICY_SEARCH TO ROLE ATO_FRAUD_ANALYST;
GRANT USAGE ON PROCEDURE ATO_FRAUD_DB.APP.ASK_ATO_AGENT(VARCHAR) TO ROLE ATO_FRAUD_ANALYST;

-- 7. Policy Engine Modification Privileges for Admin
GRANT ALL PRIVILEGES ON SCHEMA ATO_FRAUD_DB.POLICY_ENGINE TO ROLE ATO_FRAUD_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA ATO_FRAUD_DB.GOVERNANCE TO ROLE ATO_FRAUD_ADMIN;
